spring:
  datasource:
    url: '@datasource.url@'
    username: '@datasource.username@'
    password: '@datasource.password@'
    driver-class-name: '@datasource.driver@'
  jpa:
    database-platform: '@datasource.platform@'
    show-sql: true
    generate-ddl: true